name: IPK Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        arch:
          - x86_64
        sdk:
          - "22.03"

    steps:
      - uses: actions/checkout@v4

      - name: Override version number
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          RELEASE_VERSION="${RELEASE_TAG#v}"
          sed -i "s/1\.0\.0/${RELEASE_VERSION}/g" openwrt-support/rtp2httpd/Makefile configure.ac

      - name: Move src to openwrt-support
        run: mv openwrt-support ../ && mkdir ../openwrt-support/rtp2httpd/src && mv ./* ../openwrt-support/rtp2httpd/src && mv ../openwrt-support ./

      - name: Build
        uses: openwrt/gh-action-sdk@v7
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}-SNAPSHOT
          FEED_DIR: ${{ github.workspace }}/openwrt-support
          NO_DEFAULT_FEEDS: true
          NO_SHFMT_CHECK: true
          PACKAGES: rtp2httpd

      - name: Upload to release assets
        run: gh release upload --repo ${{ github.repository }} ${{ github.event.release.tag_name }} bin/packages/${{ matrix.arch }}/action/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
